.before_script_default: &before_script_default
  # Extract the APT cached packages, to void download those each time
  - |
      if test -f apt-cache.tar.gz; then
        mv apt-cache.tar.gz /apt-cache.tar.gz
        cd / && tar xf apt-cache.tar.gz
        cd $CI_PROJECT_DIR
       fi
  - apt-get update -qq && apt-get install -y -qq wget gpg xz-utils ntp

.after_script_default: &after_script_default
  - tar cf apt-cache.tar.gz /var/cache/apt

.before_script_node: &before_script_node
  - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - . "$NVM_DIR/nvm.sh"
  - touch $HOME/.npmrc
  # Allow npm scripts as root
  - echo "unsafe-perm=true" > $HOME/.npmrc

.before_script_guile: &before_script_guile
  - |
      if test -f guix-cache.tar.gz; then
        cd / && tar xf guix-cache.tar.gz
        cd $CI_PROJECT_DIR
      else
        wget https://sv.gnu.org/people/viewgpg.php?user_id=15145 -qO - | gpg --import -
        wget https://git.savannah.gnu.org/cgit/guix.git/plain/etc/guix-install.sh
        chmod ugo+x guix-install.sh
        (echo ""; echo "y") | ./guix-install.sh
      fi
  - source /root/.config/guix/current/etc/profile
  - guix-daemon --build-users-group=guixbuild --disable-chroot &
  - guix pull

.after_script_guile: &after_script_guile
  #- cp $(guix pack -C gzip guile -S /opt/bin=bin) guix-cache.tar.xz
  - tar cf guix-cache.tar.gz /var/guix /gnu

.job_node_definition: &job_node_definition
  before_script:
    - *before_script_default
    - *before_script_node

.job_guile_definition: &job_guile_definition
  before_script:
    - *before_script_default
    - *before_script_guile

  after_script:
    - *after_script_default
    - *after_script_guile

default:
  before_script:
    - *before_script_default
  after_script:
    - *after_script_default

  cache:
    key:
      files:
        - guix.scm
        - package.json
    paths:
      - guix-cache.tar.gz
      - apt-cache.tar.gz

stages:
- test
- update

test_node10:
  <<: *job_node_definition
  stage: test
  except:
    - schedules
  script:
    - echo $(pwd)
    - nvm install 10
    - npm install

test_node12:
  <<: *job_node_definition
  stage: test
  except:
    - schedules
  script:
    - nvm install 12
    - npm install

test_node14:
  <<: *job_node_definition
  stage: test
  except:
    - schedules
  script:
    - nvm install 14
    - npm install

test_guile3:
  <<: *job_guile_definition
  stage: test
  except:
    - schedules
  script:
    - guix install guile@3 || guix install guile

update_dependencies:
  allow_failure: true
  stage: update
  only:
    - schedules
  cache:
    paths:
    - ${HOME}/.npm
    - ${HOME}/.nvm
  script:
    - nvm install 14
    - npm install -g renovate@latest
    - renovate --platform gitlab --endpoint https://framagit.org/api/v4 --token ${GITLAB_AUTH_TOKEN} --labels=renovate,dependency compa/compa
