before_script:
  - apt-get update -qq && apt-get install -y -qq graphicsmagick wget sudo
  - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - . "$NVM_DIR/nvm.sh"
  - touch $HOME/.npmrc
  # Allow npm scripts as root
  - echo "unsafe-perm=true" > $HOME/.npmrc

stages:
- test
- update

test_node4:
  stage: test
  except:
    - schedules
  script:
    - nvm install 4
    - npm install
    - npm run test
    - npm run test:install
    - npm run test:coverage

test_node5:
  stage: test
  except:
    - schedules
  script:
    - nvm install 5
    - npm install
    - npm run test
    - npm run test:install

test_node6:
  stage: test
  except:
    - schedules
  script:
    - nvm install 6
    - npm install
    - npm run test
    - npm run test:install

test_node7:
  stage: test
  except:
    - schedules
  script:
    - nvm install 7
    - npm install
    - npm run test
    - npm run test:install

test_node8:
  stage: test
  except:
    - schedules
  script:
    - nvm install 8
    - npm install
    - npm run test
    - npm run test:install

update_dependencies:
  allow_failure: true
  stage: update
  only:
    - schedules
  cache:
    paths:
    - ${HOME}/.npm
    - ${HOME}/.nvm
  script:
    - nvm install 8
    - npm install -g renovate@latest
    - renovate --platform gitlab --endpoint https://framagit.org/api/v4 --token ${GITLAB_AUTH_TOKEN} --labels=renovate,dependency
